blank_issues_enabled: false
contact_links:
  - name: NDA / VDR (private form)
    url: https://docs.google.com/forms/d/e/1FAIpQLScV2Ti592K3Za2r_WLUd0E6xSvCEVnlEOxYd6OGgbpJm0ADlg/viewform?usp=header
    about: Private channel for enterprise/under-NDA discussions.
  - name: Q&A / General Discussion
    url: https://github.com/kodomonocch1/see_proto/discussions/categories/q-a
    about: Public Q&A. Please do NOT include company names or secrets.
