name: "signal: star"

on:
  watch:
    types: [started]

permissions:
  contents: write

jobs:
  append_star_csv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Append to signals/stars.csv
        run: |
          mkdir -p signals
          TS=$(date -u "+%Y-%m-%dT%H:%M:%SZ")
          USER="${{ github.actor }}"
          echo "${TS},${USER}" >> signals/stars.csv

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add signals/stars.csv
          git commit -m "signal: star by ${{ github.actor }}" || echo "No changes to commit"
          git push
