name: "signal: star (private log)"

on:
  watch:
    types: [started]

permissions:
  contents: read

jobs:
  append_private_log:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare vars
        run: |
          echo "TS=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV
          echo "ACTOR=${{ github.actor }}" >> $GITHUB_ENV
          echo "REPO=${{ github.repository }}" >> $GITHUB_ENV

      - name: Clone private signals repo
        run: |
          git clone https://x-access-token:${{ secrets.SIGNALS_PAT }}@github.com/${{ secrets.SIGNALS_REPO }} signals_repo
          cd signals_repo
          git config user.name "signals-bot"
          git config user.email "signals-bot@users.noreply.github.com"
          mkdir -p stars
          touch stars/stars.csv

      - name: Append row and push
        run: |
          cd signals_repo
          echo "${TS},${ACTOR},${REPO}" >> stars/stars.csv
          git add stars/stars.csv
          git commit -m "star: ${ACTOR} on ${REPO} at ${TS}" || echo "No changes"
          git push origin "${{ secrets.SIGNALS_BRANCH || 'main' }}"
