name: signal-star
on:
  watch: { types: [started] }   # Star されたら起動
jobs:
  log:
    runs-on: ubuntu-latest
    permissions: { contents: write, issues: write }
    steps:
      - uses: actions/checkout@v4
      - run: |
          mkdir -p signals
          echo "$(date -u +'%FT%TZ'),${{ github.actor }}" >> signals/stars.csv
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add signals/stars.csv
          git commit -m "signal: star by ${{ github.actor }}" || echo "no changes"
          git push
      - uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.create({
              owner: context.repo.owner, repo: context.repo.repo,
              title: `Signal: ⭐ by ${context.actor}`,
              body: `https://github.com/${context.actor}\n次: 本人特定→非営業1通`,
              labels: ['signal','star']
            });
